"""initial migration

Revision ID: ed679a9c06f1
Revises: 20231206_add_display_name
Create Date: 2024-11-22 14:35:45.267819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed679a9c06f1'
down_revision = '20231206_add_display_name'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
